# Generated by Django 4.1 on 2022-08-31 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTripModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('basetripmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='travel.basetripmodel')),
            ],
            bases=('travel.basetripmodel',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('basetripmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='travel.basetripmodel')),
                ('scheduled_visit_date', models.DateTimeField(verbose_name='date published')),
                ('trips', models.ManyToManyField(to='travel.trip')),
            ],
            bases=('travel.basetripmodel',),
        ),
    ]
