# Generated by Django 4.1 on 2022-08-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='scheduled_visit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Visit Date'),
        ),
        migrations.AlterField(
            model_name='location',
            name='trips',
            field=models.ManyToManyField(blank=True, null=True, to='travel.trip'),
        ),
    ]
